import styled from "styled-components";
import Head from "next/head";
/* Components */
import { useTask } from "../context/TaskContext";
import AddTask from "../components/AddTask";
import Task from "../components/Task";

const TaskDetails = styled.p`
  margin: 30px 0;
  text-align: center;
  span {
    font-weight: 500;
  }
`;

export default function Home() {
  const { tasks } = useTask();

  return (
    <div>
      <Head>
        <title>{tasks.length === 0 ? "Create your first task" : "Home"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TaskDetails>
        Your tasks: <span>{tasks.length}</span>
      </TaskDetails>
      <Task />
      <AddTask />
    </div>
  );
}
